name: UltraRoyales
version: ${version}
main: dev.zxdzero.UltraRoyales.UltraRoyales
api-version: '1.21'
authors: [ Puzzle_Dude98 ]
depend: [ZxdzeroEvents]
commands:
  arrowaura:
    description: cool
    permission: ultraroyales.command.arrowaura
  bingoreset:
    description: cool
    permission: ultraroyales.command.bingoreset